import '../src/types/global';

// Exported from a development build. Copy paste of raw state data

export const mockState: IAppState = {
  formDesigner: {
    layout: {
      components: {
        '4ffba98b-8066-4745-a1c6-b20bec8c67f5': {
          component: 'Header',
          itemType: 'COMPONENT',
          title: 'Awesome.Header',
          size: 'L'
        } as any,
        'f5a1b72e-a761-4c7f-b2ef-6e4bedfecc45': {
          component: 'Input',
          itemType: 'COMPONENT',
          title: 'Awesome.Input.Postnummer',
          dataModelBinding: 'soeker.postadresse2.poststed.postnummer'
        } as any,
        '4d32d5f8-7870-4632-a1f7-bb175e52490f': {
          component: 'Input',
          itemType: 'COMPONENT',
          title: 'Awesome-Input.Poststed',
          dataModelBinding: 'soeker.postadresse2.poststed.poststedsnavn'
        } as any
      },
      containers: {
        '8ed83506-6828-40a3-ac18-0ae58cdd3b7b': {
          repeating: false,
          dataModelGroup: null
        }
      },
      order: {
        '8ed83506-6828-40a3-ac18-0ae58cdd3b7b': [
          '4ffba98b-8066-4745-a1c6-b20bec8c67f5',
          'f5a1b72e-a761-4c7f-b2ef-6e4bedfecc45',
          '4d32d5f8-7870-4632-a1f7-bb175e52490f'
        ]
      },
      fetching: false,
      fetched: true,
      error: null,
      saving: false,
      unSavedChanges: false,
      activeContainer: ''
    }
  },
  formFiller: {
    formData: {
      'soeker.postadresse2.poststed.postnummer': '1890',
      'soeker.postadresse2.poststed.poststedsnavn': 'RAKKESTAD'
    },
    validationErrors: {},
    unsavedChanges: true
  },
  serviceConfigurations: {
    APIs: {
      connections: {
        '356bbb10-e294-11e8-b02e-f5fb488958f8': {
          externalApiId: 'id1',
          codeListId: null,
          clientParams: {
            pnr: 'soeker.postadresse2.poststed.postnummer'
          },
          metaParams: {
            clientUrl: 'test'
          },
          apiResponseMapping: {
            'soeker.postadresse2.poststed.poststedsnavn': {
              mappingKey: 'result'
            }
          }
        },
      },
      externalApisById: {
        id1: {
          id: 'id1',
          name: 'Bring postnummer API',
          type: 'value',
          shortname: 'Postnummer',
          uri: 'https://api.bring.com/shippingguide/api/postalCode.json?',
          description: 'Api for å hente poststed basert på postnummer',
          clientParams: {
            pnr: {
              type: 'queryString',
              name: 'pnr',
              value: '',
              required: true,
              example: 'Example: 2050'
            }
          },
          metaParams: {
            clientUrl: {
              type: 'queryString',
              name: 'clientUrl',
              value: '',
              required: true,
              example: 'Example: http://www.sitename.com',
              urlEncode: true
            }
          }
        },
        id2: {
          id: 'id2',
          name: 'SSB kommuneliste API',
          type: 'list',
          shortname: 'Kommuneliste',
          uri: 'http://data.ssb.no/api/klass/v1/classifications/131/codes?',
          description: 'Api for å hente liste over kommuner i Norge gylidig i gitt tidsrom',
          clientParams: {},
          metaParams: {
            from: {
              type: 'queryString',
              name: 'from',
              value: '2018-01-01',
              required: true,
              example: '2018-01-01',
              urlEncode: false
            },
            to: {
              type: 'queryString',
              name: 'to',
              value: '2018-08-01',
              required: true,
              example: '2018-08-01',
              urlEncode: false
            }
          }
        }
      },
      externalApisIds: [
        'id1',
        'id2'
      ],
      availableCodeLists: null
    },
    ruleConnection: {} as any,
    conditionalRendering: {} as any,
    manageServiceConfiguration: {
      fetching: false,
      fetched: true,
      error: null,
      saving: false,
      saved: true
    }
  },
  appData: {
    appConfig: {
      designMode: true
    },
    dataModel: {
      model: [
        {
          ID: 'melding.dataFormatProvider',
          ParentElement: 'melding',
          TypeName: null,
          Name: 'dataFormatProvider',
          DataBindingName: null,
          XPath: '/melding/dataFormatProvider',
          Restrictions: {},
          Choices: null,
          Type: 'Attribute',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 0,
          MinOccurs: 0,
          XName: 'dataFormatProvider',
          IsTagContent: false,
          FixedValue: 'GMS',
          IsReadOnly: false
        },
        {
          ID: 'melding.dataFormatId',
          ParentElement: 'melding',
          TypeName: null,
          Name: 'dataFormatId',
          DataBindingName: null,
          XPath: '/melding/dataFormatId',
          Restrictions: {},
          Choices: null,
          Type: 'Attribute',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 0,
          MinOccurs: 0,
          XName: 'dataFormatId',
          IsTagContent: false,
          FixedValue: '0033',
          IsReadOnly: false
        },
        {
          ID: 'melding.dataFormatVersion',
          ParentElement: 'melding',
          TypeName: null,
          Name: 'dataFormatVersion',
          DataBindingName: null,
          XPath: '/melding/dataFormatVersion',
          Restrictions: {},
          Choices: null,
          Type: 'Attribute',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 0,
          MinOccurs: 0,
          XName: 'dataFormatVersion',
          IsTagContent: false,
          FixedValue: '150722',
          IsReadOnly: false
        },
        {
          ID: 'melding.soeknad.tollkredittBeloep',
          ParentElement: 'melding.soeknad',
          TypeName: 'Heltall',
          Name: 'tollkredittBeloep',
          DataBindingName: 'soeknad.tollkredittBeloep',
          XPath: '/melding/soeknad/tollkredittBeloep',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'Integer',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 1,
          XName: 'tollkredittBeloep',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeknad.tollRegion',
          ParentElement: 'melding.soeknad',
          TypeName: 'Tekst',
          Name: 'tollRegion',
          DataBindingName: 'soeknad.tollRegion',
          XPath: '/melding/soeknad/tollRegion',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'tollRegion',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeknad',
          ParentElement: 'melding',
          TypeName: 'Soeknad',
          Name: 'soeknad',
          DataBindingName: 'soeknad',
          XPath: '/melding/soeknad',
          Restrictions: {},
          Choices: null,
          Type: 'Group',
          XsdValueType: null,
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 1,
          XName: 'soeknad',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.foretaketsNavn',
          ParentElement: 'melding.soeker',
          TypeName: 'Organisasjonsnavn',
          Name: 'foretaketsNavn',
          DataBindingName: 'soeker.foretaketsNavn',
          XPath: '/melding/soeker/foretaketsNavn',
          Restrictions: {
            maxLength: {
              Value: '100',
              ErrortText: null
            }
          },
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 1,
          XName: 'foretaketsNavn',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.besoeksadresse.adressenavn',
          ParentElement: 'melding.soeker.besoeksadresse',
          TypeName: 'Tekst',
          Name: 'adressenavn',
          DataBindingName: 'soeker.besoeksadresse.adressenavn',
          XPath: '/melding/soeker/besoeksadresse/adressenavn',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'adressenavn',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.besoeksadresse.adressenummer.husnummer',
          ParentElement: 'melding.soeker.besoeksadresse.adressenummer',
          TypeName: 'Tekst',
          Name: 'husnummer',
          DataBindingName: 'soeker.besoeksadresse.adressenummer.husnummer',
          XPath: '/melding/soeker/besoeksadresse/adressenummer/husnummer',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 1,
          XName: 'husnummer',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.besoeksadresse.adressenummer.husbokstav2',
          ParentElement: 'melding.soeker.besoeksadresse.adressenummer',
          TypeName: 'Tekst2',
          Name: 'husbokstav2',
          DataBindingName: 'soeker.besoeksadresse.adressenummer.husbokstav2',
          XPath: '/melding/soeker/besoeksadresse/adressenummer/husbokstav2',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'husbokstav',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.besoeksadresse.adressenummer',
          ParentElement: 'melding.soeker.besoeksadresse',
          TypeName: 'Adressenummer',
          Name: 'adressenummer',
          DataBindingName: 'soeker.besoeksadresse.adressenummer',
          XPath: '/melding/soeker/besoeksadresse/adressenummer',
          Restrictions: {},
          Choices: null,
          Type: 'Group',
          XsdValueType: null,
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'adressenummer',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.besoeksadresse.poststed.poststedsnavn',
          ParentElement: 'melding.soeker.besoeksadresse.poststed',
          TypeName: 'Tekst',
          Name: 'poststedsnavn',
          DataBindingName: 'soeker.besoeksadresse.poststed.poststedsnavn',
          XPath: '/melding/soeker/besoeksadresse/poststed/poststedsnavn',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'poststedsnavn',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.besoeksadresse.poststed.postnummer',
          ParentElement: 'melding.soeker.besoeksadresse.poststed',
          TypeName: 'Postnummer',
          Name: 'postnummer',
          DataBindingName: 'soeker.besoeksadresse.poststed.postnummer',
          XPath: '/melding/soeker/besoeksadresse/poststed/postnummer',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'postnummer',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.besoeksadresse.poststed',
          ParentElement: 'melding.soeker.besoeksadresse',
          TypeName: 'Poststed',
          Name: 'poststed',
          DataBindingName: 'soeker.besoeksadresse.poststed',
          XPath: '/melding/soeker/besoeksadresse/poststed',
          Restrictions: {},
          Choices: null,
          Type: 'Group',
          XsdValueType: null,
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'poststed',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.besoeksadresse',
          ParentElement: 'melding.soeker',
          TypeName: 'Vegadresse',
          Name: 'besoeksadresse',
          DataBindingName: 'soeker.besoeksadresse',
          XPath: '/melding/soeker/besoeksadresse',
          Restrictions: {},
          Choices: null,
          Type: 'Group',
          XsdValueType: null,
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'besoeksadresse',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.postadresse2.adressenavn',
          ParentElement: 'melding.soeker.postadresse2',
          TypeName: 'Tekst',
          Name: 'adressenavn',
          DataBindingName: 'soeker.postadresse2.adressenavn',
          XPath: '/melding/soeker/postadresse2/adressenavn',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'adressenavn',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.postadresse2.adressenummer.husnummer',
          ParentElement: 'melding.soeker.postadresse2.adressenummer',
          TypeName: 'Tekst',
          Name: 'husnummer',
          DataBindingName: 'soeker.postadresse2.adressenummer.husnummer',
          XPath: '/melding/soeker/postadresse2/adressenummer/husnummer',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 1,
          XName: 'husnummer',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.postadresse2.adressenummer.husbokstav2',
          ParentElement: 'melding.soeker.postadresse2.adressenummer',
          TypeName: 'Tekst2',
          Name: 'husbokstav2',
          DataBindingName: 'soeker.postadresse2.adressenummer.husbokstav2',
          XPath: '/melding/soeker/postadresse2/adressenummer/husbokstav2',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'husbokstav',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.postadresse2.adressenummer',
          ParentElement: 'melding.soeker.postadresse2',
          TypeName: 'Adressenummer',
          Name: 'adressenummer',
          DataBindingName: 'soeker.postadresse2.adressenummer',
          XPath: '/melding/soeker/postadresse2/adressenummer',
          Restrictions: {},
          Choices: null,
          Type: 'Group',
          XsdValueType: null,
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'adressenummer',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.postadresse2.poststed.poststedsnavn',
          ParentElement: 'melding.soeker.postadresse2.poststed',
          TypeName: 'Tekst',
          Name: 'poststedsnavn',
          DataBindingName: 'soeker.postadresse2.poststed.poststedsnavn',
          XPath: '/melding/soeker/postadresse2/poststed/poststedsnavn',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'poststedsnavn',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.postadresse2.poststed.postnummer',
          ParentElement: 'melding.soeker.postadresse2.poststed',
          TypeName: 'Postnummer',
          Name: 'postnummer',
          DataBindingName: 'soeker.postadresse2.poststed.postnummer',
          XPath: '/melding/soeker/postadresse2/poststed/postnummer',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'postnummer',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.postadresse2.poststed',
          ParentElement: 'melding.soeker.postadresse2',
          TypeName: 'Poststed',
          Name: 'poststed',
          DataBindingName: 'soeker.postadresse2.poststed',
          XPath: '/melding/soeker/postadresse2/poststed',
          Restrictions: {},
          Choices: null,
          Type: 'Group',
          XsdValueType: null,
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'poststed',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.postadresse2',
          ParentElement: 'melding.soeker',
          TypeName: 'Vegadresse2',
          Name: 'postadresse2',
          DataBindingName: 'soeker.postadresse2',
          XPath: '/melding/soeker/postadresse2',
          Restrictions: {},
          Choices: null,
          Type: 'Group',
          XsdValueType: null,
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'postadresse',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.telefonnr',
          ParentElement: 'melding.soeker',
          TypeName: 'Telefonnummer',
          Name: 'telefonnr',
          DataBindingName: 'soeker.telefonnr',
          XPath: '/melding/soeker/telefonnr',
          Restrictions: {
            maxLength: {
              Value: '20',
              ErrortText: null
            }
          },
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'telefonnr',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.epost',
          ParentElement: 'melding.soeker',
          TypeName: 'Epostadresse',
          Name: 'epost',
          DataBindingName: 'soeker.epost',
          XPath: '/melding/soeker/epost',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'epost',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.organisajonsnr',
          ParentElement: 'melding.soeker',
          TypeName: 'Organisasjonsnummer',
          Name: 'organisajonsnr',
          DataBindingName: 'soeker.organisajonsnr',
          XPath: '/melding/soeker/organisajonsnr',
          Restrictions: {
            maxLength: {
              Value: '9',
              ErrortText: null
            },
            pattern: {
              Value: '[0-9]+',
              ErrortText: null
            }
          },
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 1,
          XName: 'organisajonsnr',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.kontaktperson.fornavn',
          ParentElement: 'melding.soeker.kontaktperson',
          TypeName: 'Navn',
          Name: 'fornavn',
          DataBindingName: 'soeker.kontaktperson.fornavn',
          XPath: '/melding/soeker/kontaktperson/fornavn',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 1,
          XName: 'fornavn',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.kontaktperson.mellomnavn2',
          ParentElement: 'melding.soeker.kontaktperson',
          TypeName: 'Navn2',
          Name: 'mellomnavn2',
          DataBindingName: 'soeker.kontaktperson.mellomnavn2',
          XPath: '/melding/soeker/kontaktperson/mellomnavn2',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'mellomnavn',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.kontaktperson.etternavn2',
          ParentElement: 'melding.soeker.kontaktperson',
          TypeName: 'Navn2',
          Name: 'etternavn2',
          DataBindingName: 'soeker.kontaktperson.etternavn2',
          XPath: '/melding/soeker/kontaktperson/etternavn2',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 1,
          XName: 'etternavn',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.kontaktperson',
          ParentElement: 'melding.soeker',
          TypeName: 'Personnavn',
          Name: 'kontaktperson',
          DataBindingName: 'soeker.kontaktperson',
          XPath: '/melding/soeker/kontaktperson',
          Restrictions: {},
          Choices: null,
          Type: 'Group',
          XsdValueType: null,
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 1,
          XName: 'kontaktperson',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.bankkonto',
          ParentElement: 'melding.soeker',
          TypeName: 'Tekst',
          Name: 'bankkonto',
          DataBindingName: 'soeker.bankkonto',
          XPath: '/melding/soeker/bankkonto',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 1,
          XName: 'bankkonto',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.mvaReg',
          ParentElement: 'melding.soeker',
          TypeName: 'Boolsk',
          Name: 'mvaReg',
          DataBindingName: 'soeker.mvaReg',
          XPath: '/melding/soeker/mvaReg',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'Boolean',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 1,
          XName: 'mvaReg',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.foretaksReg2',
          ParentElement: 'melding.soeker',
          TypeName: 'Boolsk2',
          Name: 'foretaksReg2',
          DataBindingName: 'soeker.foretaksReg2',
          XPath: '/melding/soeker/foretaksReg2',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'Boolean',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 1,
          XName: 'foretaksReg',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.enhetsReg2',
          ParentElement: 'melding.soeker',
          TypeName: 'Boolsk2',
          Name: 'enhetsReg2',
          DataBindingName: 'soeker.enhetsReg2',
          XPath: '/melding/soeker/enhetsReg2',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'Boolean',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 1,
          XName: 'enhetsReg',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.utlandsReg2',
          ParentElement: 'melding.soeker',
          TypeName: 'Boolsk2',
          Name: 'utlandsReg2',
          DataBindingName: 'soeker.utlandsReg2',
          XPath: '/melding/soeker/utlandsReg2',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'Boolean',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 1,
          XName: 'utlandsReg',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.regNrUtland2',
          ParentElement: 'melding.soeker',
          TypeName: 'Tekst2',
          Name: 'regNrUtland2',
          DataBindingName: 'soeker.regNrUtland2',
          XPath: '/melding/soeker/regNrUtland2',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'regNrUtland',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.navnPaaRegisterUtland2',
          ParentElement: 'melding.soeker',
          TypeName: 'Tekst2',
          Name: 'navnPaaRegisterUtland2',
          DataBindingName: 'soeker.navnPaaRegisterUtland2',
          XPath: '/melding/soeker/navnPaaRegisterUtland2',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'navnPaaRegisterUtland',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker.telefax2',
          ParentElement: 'melding.soeker',
          TypeName: 'Telefonnummer2',
          Name: 'telefax2',
          DataBindingName: 'soeker.telefax2',
          XPath: '/melding/soeker/telefax2',
          Restrictions: {
            maxLength: {
              Value: '20',
              ErrortText: null
            }
          },
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'telefax',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.soeker',
          ParentElement: 'melding',
          TypeName: 'Soeker',
          Name: 'soeker',
          DataBindingName: 'soeker',
          XPath: '/melding/soeker',
          Restrictions: {},
          Choices: null,
          Type: 'Group',
          XsdValueType: null,
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 1,
          XName: 'soeker',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.foretaketsNavn',
          ParentElement: 'melding.paaVegneAv',
          TypeName: 'Organisasjonsnavn',
          Name: 'foretaketsNavn',
          DataBindingName: 'paaVegneAv.foretaketsNavn',
          XPath: '/melding/paaVegneAv/foretaketsNavn',
          Restrictions: {
            maxLength: {
              Value: '100',
              ErrortText: null
            }
          },
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'foretaketsNavn',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.besoeksadresse.adressenavn',
          ParentElement: 'melding.paaVegneAv.besoeksadresse',
          TypeName: 'Tekst',
          Name: 'adressenavn',
          DataBindingName: 'paaVegneAv.besoeksadresse.adressenavn',
          XPath: '/melding/paaVegneAv/besoeksadresse/adressenavn',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'adressenavn',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.besoeksadresse.adressenummer.husnummer',
          ParentElement: 'melding.paaVegneAv.besoeksadresse.adressenummer',
          TypeName: 'Tekst',
          Name: 'husnummer',
          DataBindingName: 'paaVegneAv.besoeksadresse.adressenummer.husnummer',
          XPath: '/melding/paaVegneAv/besoeksadresse/adressenummer/husnummer',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 1,
          XName: 'husnummer',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.besoeksadresse.adressenummer.husbokstav2',
          ParentElement: 'melding.paaVegneAv.besoeksadresse.adressenummer',
          TypeName: 'Tekst2',
          Name: 'husbokstav2',
          DataBindingName: 'paaVegneAv.besoeksadresse.adressenummer.husbokstav2',
          XPath: '/melding/paaVegneAv/besoeksadresse/adressenummer/husbokstav2',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'husbokstav',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.besoeksadresse.adressenummer',
          ParentElement: 'melding.paaVegneAv.besoeksadresse',
          TypeName: 'Adressenummer',
          Name: 'adressenummer',
          DataBindingName: 'paaVegneAv.besoeksadresse.adressenummer',
          XPath: '/melding/paaVegneAv/besoeksadresse/adressenummer',
          Restrictions: {},
          Choices: null,
          Type: 'Group',
          XsdValueType: null,
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'adressenummer',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.besoeksadresse.poststed.poststedsnavn',
          ParentElement: 'melding.paaVegneAv.besoeksadresse.poststed',
          TypeName: 'Tekst',
          Name: 'poststedsnavn',
          DataBindingName: 'paaVegneAv.besoeksadresse.poststed.poststedsnavn',
          XPath: '/melding/paaVegneAv/besoeksadresse/poststed/poststedsnavn',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'poststedsnavn',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.besoeksadresse.poststed.postnummer',
          ParentElement: 'melding.paaVegneAv.besoeksadresse.poststed',
          TypeName: 'Postnummer',
          Name: 'postnummer',
          DataBindingName: 'paaVegneAv.besoeksadresse.poststed.postnummer',
          XPath: '/melding/paaVegneAv/besoeksadresse/poststed/postnummer',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'postnummer',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.besoeksadresse.poststed',
          ParentElement: 'melding.paaVegneAv.besoeksadresse',
          TypeName: 'Poststed',
          Name: 'poststed',
          DataBindingName: 'paaVegneAv.besoeksadresse.poststed',
          XPath: '/melding/paaVegneAv/besoeksadresse/poststed',
          Restrictions: {},
          Choices: null,
          Type: 'Group',
          XsdValueType: null,
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'poststed',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.besoeksadresse',
          ParentElement: 'melding.paaVegneAv',
          TypeName: 'Vegadresse',
          Name: 'besoeksadresse',
          DataBindingName: 'paaVegneAv.besoeksadresse',
          XPath: '/melding/paaVegneAv/besoeksadresse',
          Restrictions: {},
          Choices: null,
          Type: 'Group',
          XsdValueType: null,
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'besoeksadresse',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.postadresse2.adressenavn',
          ParentElement: 'melding.paaVegneAv.postadresse2',
          TypeName: 'Tekst',
          Name: 'adressenavn',
          DataBindingName: 'paaVegneAv.postadresse2.adressenavn',
          XPath: '/melding/paaVegneAv/postadresse2/adressenavn',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'adressenavn',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.postadresse2.adressenummer.husnummer',
          ParentElement: 'melding.paaVegneAv.postadresse2.adressenummer',
          TypeName: 'Tekst',
          Name: 'husnummer',
          DataBindingName: 'paaVegneAv.postadresse2.adressenummer.husnummer',
          XPath: '/melding/paaVegneAv/postadresse2/adressenummer/husnummer',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 1,
          XName: 'husnummer',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.postadresse2.adressenummer.husbokstav2',
          ParentElement: 'melding.paaVegneAv.postadresse2.adressenummer',
          TypeName: 'Tekst2',
          Name: 'husbokstav2',
          DataBindingName: 'paaVegneAv.postadresse2.adressenummer.husbokstav2',
          XPath: '/melding/paaVegneAv/postadresse2/adressenummer/husbokstav2',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'husbokstav',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.postadresse2.adressenummer',
          ParentElement: 'melding.paaVegneAv.postadresse2',
          TypeName: 'Adressenummer',
          Name: 'adressenummer',
          DataBindingName: 'paaVegneAv.postadresse2.adressenummer',
          XPath: '/melding/paaVegneAv/postadresse2/adressenummer',
          Restrictions: {},
          Choices: null,
          Type: 'Group',
          XsdValueType: null,
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'adressenummer',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.postadresse2.poststed.poststedsnavn',
          ParentElement: 'melding.paaVegneAv.postadresse2.poststed',
          TypeName: 'Tekst',
          Name: 'poststedsnavn',
          DataBindingName: 'paaVegneAv.postadresse2.poststed.poststedsnavn',
          XPath: '/melding/paaVegneAv/postadresse2/poststed/poststedsnavn',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'poststedsnavn',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.postadresse2.poststed.postnummer',
          ParentElement: 'melding.paaVegneAv.postadresse2.poststed',
          TypeName: 'Postnummer',
          Name: 'postnummer',
          DataBindingName: 'paaVegneAv.postadresse2.poststed.postnummer',
          XPath: '/melding/paaVegneAv/postadresse2/poststed/postnummer',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'postnummer',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.postadresse2.poststed',
          ParentElement: 'melding.paaVegneAv.postadresse2',
          TypeName: 'Poststed',
          Name: 'poststed',
          DataBindingName: 'paaVegneAv.postadresse2.poststed',
          XPath: '/melding/paaVegneAv/postadresse2/poststed',
          Restrictions: {},
          Choices: null,
          Type: 'Group',
          XsdValueType: null,
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'poststed',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.postadresse2',
          ParentElement: 'melding.paaVegneAv',
          TypeName: 'Vegadresse2',
          Name: 'postadresse2',
          DataBindingName: 'paaVegneAv.postadresse2',
          XPath: '/melding/paaVegneAv/postadresse2',
          Restrictions: {},
          Choices: null,
          Type: 'Group',
          XsdValueType: null,
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'postadresse',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.telefonnr',
          ParentElement: 'melding.paaVegneAv',
          TypeName: 'Telefonnummer',
          Name: 'telefonnr',
          DataBindingName: 'paaVegneAv.telefonnr',
          XPath: '/melding/paaVegneAv/telefonnr',
          Restrictions: {
            maxLength: {
              Value: '20',
              ErrortText: null
            }
          },
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'telefonnr',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.epostadresse',
          ParentElement: 'melding.paaVegneAv',
          TypeName: 'Epostadresse',
          Name: 'epostadresse',
          DataBindingName: 'paaVegneAv.epostadresse',
          XPath: '/melding/paaVegneAv/epostadresse',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'epostadresse',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.organisasjonsnr',
          ParentElement: 'melding.paaVegneAv',
          TypeName: 'Organisasjonsnummer',
          Name: 'organisasjonsnr',
          DataBindingName: 'paaVegneAv.organisasjonsnr',
          XPath: '/melding/paaVegneAv/organisasjonsnr',
          Restrictions: {
            maxLength: {
              Value: '9',
              ErrortText: null
            },
            pattern: {
              Value: '[0-9]+',
              ErrortText: null
            }
          },
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'organisasjonsnr',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.kontaktperson.fornavn',
          ParentElement: 'melding.paaVegneAv.kontaktperson',
          TypeName: 'Navn',
          Name: 'fornavn',
          DataBindingName: 'paaVegneAv.kontaktperson.fornavn',
          XPath: '/melding/paaVegneAv/kontaktperson/fornavn',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 1,
          XName: 'fornavn',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.kontaktperson.mellomnavn2',
          ParentElement: 'melding.paaVegneAv.kontaktperson',
          TypeName: 'Navn2',
          Name: 'mellomnavn2',
          DataBindingName: 'paaVegneAv.kontaktperson.mellomnavn2',
          XPath: '/melding/paaVegneAv/kontaktperson/mellomnavn2',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'mellomnavn',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.kontaktperson.etternavn2',
          ParentElement: 'melding.paaVegneAv.kontaktperson',
          TypeName: 'Navn2',
          Name: 'etternavn2',
          DataBindingName: 'paaVegneAv.kontaktperson.etternavn2',
          XPath: '/melding/paaVegneAv/kontaktperson/etternavn2',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 1,
          XName: 'etternavn',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.kontaktperson',
          ParentElement: 'melding.paaVegneAv',
          TypeName: 'Personnavn',
          Name: 'kontaktperson',
          DataBindingName: 'paaVegneAv.kontaktperson',
          XPath: '/melding/paaVegneAv/kontaktperson',
          Restrictions: {},
          Choices: null,
          Type: 'Group',
          XsdValueType: null,
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'kontaktperson',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.bankkonto',
          ParentElement: 'melding.paaVegneAv',
          TypeName: 'Tekst',
          Name: 'bankkonto',
          DataBindingName: 'paaVegneAv.bankkonto',
          XPath: '/melding/paaVegneAv/bankkonto',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'String',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'bankkonto',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.mvaReg',
          ParentElement: 'melding.paaVegneAv',
          TypeName: 'Boolsk',
          Name: 'mvaReg',
          DataBindingName: 'paaVegneAv.mvaReg',
          XPath: '/melding/paaVegneAv/mvaReg',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'Boolean',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'mvaReg',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.foretaksReg2',
          ParentElement: 'melding.paaVegneAv',
          TypeName: 'Boolsk2',
          Name: 'foretaksReg2',
          DataBindingName: 'paaVegneAv.foretaksReg2',
          XPath: '/melding/paaVegneAv/foretaksReg2',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'Boolean',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'foretaksReg',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv.enhetsReg2',
          ParentElement: 'melding.paaVegneAv',
          TypeName: 'Boolsk2',
          Name: 'enhetsReg2',
          DataBindingName: 'paaVegneAv.enhetsReg2',
          XPath: '/melding/paaVegneAv/enhetsReg2',
          Restrictions: {},
          Choices: null,
          Type: 'Field',
          XsdValueType: 'Boolean',
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'enhetsReg',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding.paaVegneAv',
          ParentElement: 'melding',
          TypeName: 'Tollkredittkunde',
          Name: 'paaVegneAv',
          DataBindingName: 'paaVegneAv',
          XPath: '/melding/paaVegneAv',
          Restrictions: {},
          Choices: null,
          Type: 'Group',
          XsdValueType: null,
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 1,
          MinOccurs: 0,
          XName: 'paaVegneAv',
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        },
        {
          ID: 'melding',
          ParentElement: null,
          TypeName: 'SoeknadOmTollkreditt',
          Name: 'melding',
          DataBindingName: null,
          XPath: '/melding',
          Restrictions: {},
          Choices: null,
          Type: 'Group',
          XsdValueType: null,
          Texts: {},
          CustomProperties: {},
          MaxOccurs: 0,
          MinOccurs: 0,
          XName: null,
          IsTagContent: false,
          FixedValue: null,
          IsReadOnly: false
        }
      ],
      fetching: false,
      fetched: true,
      error: null
    },
    textResources: {
      resources: [
        {
          id: 'Awesome-Input.Poststed',
          value: 'Poststed'
        },
        {
          id: 'Awesome.Header',
          value: 'Awesome'
        },
        {
          id: 'Awesome.Input.Postnummer',
          value: 'Postnummer'
        }
      ],
      language: 'nb-NO',
      fetching: false,
      fetched: true,
      error: null
    },
    ruleModel: {
      model: [
        {
          name: 'sum',
          inputs: {
            a: 'a',
            b: 'b',
            c: 'c'
          },
          type: 'rule'
        },
        {
          name: 'fullName',
          inputs: {
            first: 'first name',
            last: 'last name'
          },
          type: 'rule'
        },
        {
          name: 'biggerThan10',
          inputs: {
            number: 'number'
          },
          type: 'condition'
        },
        {
          name: 'smallerThan10',
          inputs: {
            number: 'number'
          },
          type: 'condition'
        },
        {
          name: 'lengthBiggerThan4',
          inputs: {
            value: 'value'
          },
          type: 'condition'
        }
      ],
      fetching: false,
      fetched: true,
      error: null
    },
    codeLists: {
      codeLists: [],
      fetching: false,
      fetched: true,
      error: null
    }
  },
  errors: {
    errorList: []
  },
  thirdPartyComponents: {
    components: null,
    error: null
  }
}
